/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const GithubOwnerLazyImport = createFileRoute("/github/$owner")();

// Create/Update Routes

const GithubOwnerLazyRoute = GithubOwnerLazyImport.update({
  path: "/github/$owner",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/github.$owner.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/github/$owner": {
      id: "/github/$owner";
      path: "/github/$owner";
      fullPath: "/github/$owner";
      preLoaderRoute: typeof GithubOwnerLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ GithubOwnerLazyRoute });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/github/$owner"
      ]
    },
    "/github/$owner": {
      "filePath": "github.$owner.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
