/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const GithubOwnerLazyImport = createFileRoute("/github/$owner")();

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const GithubOwnerLazyRoute = GithubOwnerLazyImport.update({
  path: "/github/$owner",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/github.$owner.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/github/$owner": {
      id: "/github/$owner";
      path: "/github/$owner";
      fullPath: "/github/$owner";
      preLoaderRoute: typeof GithubOwnerLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/github/$owner": typeof GithubOwnerLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/github/$owner": typeof GithubOwnerLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/github/$owner": typeof GithubOwnerLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/github/$owner";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/github/$owner";
  id: "__root__" | "/" | "/github/$owner";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GithubOwnerLazyRoute: typeof GithubOwnerLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubOwnerLazyRoute: GithubOwnerLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/github/$owner"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/github/$owner": {
      "filePath": "github.$owner.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
